name: Package Test

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        php:
          - '5.6'
          - '7.0'
          - '7.1'
          - '7.2'
        coverage: [ 'none' ]
        exclude:
          - php: '7.2'
        include:
          - php: '7.2'
            coverage: 'xdebug'

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage }}
          extensions: curl, sockets

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run linting
        run: composer lint

      - name: Run test suite
        run: vendor/bin/phpunit -v
